<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Gabriel Germano dos Santos - 123110263">
<meta name="author" content="Denis Almeida Ferreira - 123210975">
<meta name="author" content="Wendel Silva Italiano de Araújo - 123111398">
<meta name="dcterms.date" content="2026-03-15">

<title>Análise - Campanha de Marketing</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Relatorio_marketing_files/libs/clipboard/clipboard.min.js"></script>
<script src="Relatorio_marketing_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Relatorio_marketing_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Relatorio_marketing_files/libs/quarto-html/popper.min.js"></script>
<script src="Relatorio_marketing_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Relatorio_marketing_files/libs/quarto-html/anchor.min.js"></script>
<link href="Relatorio_marketing_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Relatorio_marketing_files/libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Relatorio_marketing_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Relatorio_marketing_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Relatorio_marketing_files/libs/bootstrap/bootstrap-293cc809d15782442e9b1098eedb6797.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introdução-à-análise" id="toc-introdução-à-análise" class="nav-link active" data-scroll-target="#introdução-à-análise"><span class="header-section-number">1</span> Introdução à análise</a></li>
  <li><a href="#dados-da-análise" id="toc-dados-da-análise" class="nav-link" data-scroll-target="#dados-da-análise"><span class="header-section-number">2</span> Dados da análise</a></li>
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados"><span class="header-section-number">3</span> Análise Exploratória dos Dados</a>
  <ul class="collapse">
  <li><a href="#limpeza-dos-dados" id="toc-limpeza-dos-dados" class="nav-link" data-scroll-target="#limpeza-dos-dados"><span class="header-section-number">3.1</span> Limpeza dos Dados</a></li>
  <li><a href="#estatísticas-descritivas" id="toc-estatísticas-descritivas" class="nav-link" data-scroll-target="#estatísticas-descritivas"><span class="header-section-number">3.2</span> Estatísticas Descritivas</a></li>
  <li><a href="#análise-gráfica" id="toc-análise-gráfica" class="nav-link" data-scroll-target="#análise-gráfica"><span class="header-section-number">3.3</span> Análise Gráfica</a>
  <ul class="collapse">
  <li><a href="#histograma" id="toc-histograma" class="nav-link" data-scroll-target="#histograma"><span class="header-section-number">3.3.1</span> Histograma</a></li>
  <li><a href="#boxplot" id="toc-boxplot" class="nav-link" data-scroll-target="#boxplot"><span class="header-section-number">3.3.2</span> Boxplot</a></li>
  <li><a href="#gráficos-de-dispersão" id="toc-gráficos-de-dispersão" class="nav-link" data-scroll-target="#gráficos-de-dispersão"><span class="header-section-number">3.3.3</span> Gráficos de Dispersão</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análises-bivariadas" id="toc-análises-bivariadas" class="nav-link" data-scroll-target="#análises-bivariadas"><span class="header-section-number">4</span> Análises Bivariadas</a>
  <ul class="collapse">
  <li><a href="#variáveis-numéricas" id="toc-variáveis-numéricas" class="nav-link" data-scroll-target="#variáveis-numéricas"><span class="header-section-number">4.1</span> Variáveis Numéricas</a>
  <ul class="collapse">
  <li><a href="#principais-destaques-e-interpretações" id="toc-principais-destaques-e-interpretações" class="nav-link" data-scroll-target="#principais-destaques-e-interpretações"><span class="header-section-number">4.1.1</span> Principais destaques e interpretações</a></li>
  </ul></li>
  <li><a href="#variáveis-categóricas" id="toc-variáveis-categóricas" class="nav-link" data-scroll-target="#variáveis-categóricas"><span class="header-section-number">4.2</span> Variáveis Categóricas</a></li>
  </ul></li>
  <li><a href="#regressão-linear" id="toc-regressão-linear" class="nav-link" data-scroll-target="#regressão-linear"><span class="header-section-number">5</span> Regressão Linear</a>
  <ul class="collapse">
  <li><a href="#multicolinearidade" id="toc-multicolinearidade" class="nav-link" data-scroll-target="#multicolinearidade"><span class="header-section-number">5.1</span> Multicolinearidade</a>
  <ul class="collapse">
  <li><a href="#modelo-a-sem-num_cliques_mil" id="toc-modelo-a-sem-num_cliques_mil" class="nav-link" data-scroll-target="#modelo-a-sem-num_cliques_mil"><span class="header-section-number">5.1.1</span> Modelo A: Sem <code>num_cliques_mil</code></a></li>
  <li><a href="#modelo-b-sem-impressoes_mil" id="toc-modelo-b-sem-impressoes_mil" class="nav-link" data-scroll-target="#modelo-b-sem-impressoes_mil"><span class="header-section-number">5.1.2</span> Modelo B: Sem <code>impressoes_mil</code></a></li>
  <li><a href="#modelo-c-sem-invest_digital" id="toc-modelo-c-sem-invest_digital" class="nav-link" data-scroll-target="#modelo-c-sem-invest_digital"><span class="header-section-number">5.1.3</span> Modelo C: Sem <code>invest_digital</code></a></li>
  <li><a href="#modelo-d-sem-num_cliques_mil-e-impressoes_mil" id="toc-modelo-d-sem-num_cliques_mil-e-impressoes_mil" class="nav-link" data-scroll-target="#modelo-d-sem-num_cliques_mil-e-impressoes_mil"><span class="header-section-number">5.1.4</span> Modelo D: Sem <code>num_cliques_mil</code> e <code>impressoes_mil</code></a></li>
  <li><a href="#modelo-e-sem-invest_digital-e-impressoes_mil" id="toc-modelo-e-sem-invest_digital-e-impressoes_mil" class="nav-link" data-scroll-target="#modelo-e-sem-invest_digital-e-impressoes_mil"><span class="header-section-number">5.1.5</span> Modelo E: Sem <code>invest_digital</code> e <code>impressoes_mil</code></a></li>
  </ul></li>
  <li><a href="#seleção-do-modelo" id="toc-seleção-do-modelo" class="nav-link" data-scroll-target="#seleção-do-modelo"><span class="header-section-number">5.2</span> Seleção do Modelo</a></li>
  </ul></li>
  <li><a href="#análise-dos-pressupostos" id="toc-análise-dos-pressupostos" class="nav-link" data-scroll-target="#análise-dos-pressupostos"><span class="header-section-number">6</span> Análise dos pressupostos</a></li>
  <li><a href="#estimativas" id="toc-estimativas" class="nav-link" data-scroll-target="#estimativas"><span class="header-section-number">7</span> Estimativas</a></li>
  <li><a href="#previsões" id="toc-previsões" class="nav-link" data-scroll-target="#previsões"><span class="header-section-number">8</span> Previsões</a></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">9</span> Conclusão</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise - Campanha de Marketing</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Gabriel Germano dos Santos - 123110263 </p>
             <p>Denis Almeida Ferreira - 123210975 </p>
             <p>Wendel Silva Italiano de Araújo - 123111398 </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução-à-análise" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução à análise</h1>
<p>Este trabalho apresenta uma análise estatística do dataset “03 - Marketing - Disponibilizar”.</p>
<p>O dataset possui variáveis categóricas e numéricas que contêm informações relacionadas às campanhas de marketing de uma empresa de e-commerce varejista. As variáveis presentes permitem uma análise detalhada sobre os fatores que influenciam a receita gerada pelas campanhas, para as quais estaremos ajustando um modelo de regressão linear múltipla.</p>
<p>O principal objetivo deste trabalho é identificar os principais fatores que influenciam a receita das campanhas de marketing, utilizando técnicas de análise exploratória e regressão linear múltipla.</p>
</section>
<section id="dados-da-análise" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Dados da análise</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Apresentação dos dados</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dados)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 207
Columns: 12
$ id                 &lt;chr&gt; "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", …
$ receita_mil        &lt;dbl&gt; 156.9, 175.6, 146.7, 82.0, 147.5, 269.1, 129.2, 127…
$ invest_digital     &lt;dbl&gt; 19.82, 30.50, 22.25, 2.72, 21.52, 46.21, 19.69, 17.…
$ invest_tradicional &lt;dbl&gt; 8.34, 12.50, 14.65, 6.25, 13.31, 4.90, 11.28, 8.59,…
$ num_promotores     &lt;dbl&gt; 4, 4, 3, 2, 5, 0, 5, 3, 0, 2, 6, 0, 6, 6, 5, 3, 2, …
$ taxa_conversao     &lt;dbl&gt; 3.77, 0.94, 1.71, 3.29, 3.29, 2.08, 1.20, 1.72, 3.6…
$ impressoes_mil     &lt;dbl&gt; 446.9, 615.6, 418.8, 93.3, 410.1, 821.8, 461.7, 419…
$ cpc                &lt;dbl&gt; 3.59, 2.83, 3.00, 3.73, 2.85, 2.29, 3.01, 3.12, 2.6…
$ num_cliques_mil    &lt;dbl&gt; 16.5, 33.1, 20.1, 0.5, 29.1, 49.1, 30.1, 23.9, 28.3…
$ duracao_dias       &lt;dbl&gt; 18, 27, 53, 36, 22, 59, 53, 27, 20, 14, 54, 27, 26,…
$ canal              &lt;chr&gt; "SEO", "E-mail", "Redes Sociais", "Redes Sociais", …
$ sazonalidade       &lt;chr&gt; "Alta", "Alta", "Baixa", "Alta", "Baixa", "Alta", "…</code></pre>
</div>
</div>
<p>A partir da base de dados, podemos visualizar as seguintes varíaveis: - <code>receita_mil</code>: receita gerada pela campanha (em milhares de R<span class="math inline">\();
- `invest_digital`: valor investido em marketing digital (em milhares de R\)</span>);<br>
- <code>cpc</code>: custo por clique (em R$);<br>
- <code>canal</code>: canal de marketing utilizado na campanha (Redes Sociais, E-mail, SEO, Display);<br>
- <code>sazonalidade</code>: período da campanha (Alta ou Baixa sazonalidade);<br>
- <code>num_cliques_mil</code>: número de cliques recebidos pela campanha (em milhares);<br>
- <code>impressoes_mil</code>: número de impressões geradas pela campanha (em milhares);<br>
- <code>num_promotores</code>: quantidade de promotores envolvidos na campanha;<br>
- <code>duracao_dias</code>: duração da campanha (em dias).</p>
</section>
<section id="análise-exploratória-dos-dados" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análise Exploratória dos Dados</h1>
<p>A análise exploratória de dados tem como objetivo compreender melhor as características da base de dados antes da aplicação de modelos estatísticos mais complexos.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dados</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(dados)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">207</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">character</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 13%">
<col style="width: 19%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">min</th>
<th style="text-align: right;">max</th>
<th style="text-align: right;">empty</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: right;">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">206</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">canal</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sazonalidade</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.97</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 6%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">receita_mil</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">162.02</td>
<td style="text-align: right;">48.26</td>
<td style="text-align: right;">46.89</td>
<td style="text-align: right;">130.35</td>
<td style="text-align: right;">164.04</td>
<td style="text-align: right;">192.93</td>
<td style="text-align: right;">273.75</td>
<td style="text-align: left;">▂▅▇▅▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">invest_digital</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">25.23</td>
<td style="text-align: right;">11.53</td>
<td style="text-align: right;">2.00</td>
<td style="text-align: right;">17.19</td>
<td style="text-align: right;">25.19</td>
<td style="text-align: right;">32.47</td>
<td style="text-align: right;">50.94</td>
<td style="text-align: left;">▃▆▇▆▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">invest_tradicional</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">8.34</td>
<td style="text-align: right;">4.78</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">5.19</td>
<td style="text-align: right;">8.34</td>
<td style="text-align: right;">11.16</td>
<td style="text-align: right;">20.30</td>
<td style="text-align: left;">▅▇▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">num_promotores</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">2.85</td>
<td style="text-align: right;">1.91</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">1.90</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">7.00</td>
<td style="text-align: left;">▆▅▇▃▃</td>
</tr>
<tr class="odd">
<td style="text-align: left;">taxa_conversao</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.34</td>
<td style="text-align: right;">2.02</td>
<td style="text-align: right;">2.52</td>
<td style="text-align: right;">3.02</td>
<td style="text-align: right;">4.61</td>
<td style="text-align: left;">▁▃▇▅▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">impressoes_mil</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">508.31</td>
<td style="text-align: right;">210.45</td>
<td style="text-align: right;">49.80</td>
<td style="text-align: right;">370.20</td>
<td style="text-align: right;">507.75</td>
<td style="text-align: right;">646.50</td>
<td style="text-align: right;">1006.90</td>
<td style="text-align: left;">▂▅▇▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cpc</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">2.97</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.46</td>
<td style="text-align: right;">2.65</td>
<td style="text-align: right;">2.96</td>
<td style="text-align: right;">3.29</td>
<td style="text-align: right;">4.37</td>
<td style="text-align: left;">▁▁▆▇▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">num_cliques_mil</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">29.70</td>
<td style="text-align: right;">13.86</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">21.50</td>
<td style="text-align: right;">29.20</td>
<td style="text-align: right;">38.90</td>
<td style="text-align: right;">64.30</td>
<td style="text-align: left;">▂▆▇▅▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">duracao_dias</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">33.58</td>
<td style="text-align: right;">15.94</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">19.00</td>
<td style="text-align: right;">33.00</td>
<td style="text-align: right;">48.00</td>
<td style="text-align: right;">60.00</td>
<td style="text-align: left;">▇▅▇▅▇</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="limpeza-dos-dados" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="limpeza-dos-dados"><span class="header-section-number">3.1</span> Limpeza dos Dados</h2>
<p>Antes da análise, foi realizada uma inspeção para identificar valores ausentes na base de dados. Observou-se que a maioria das variáveis numéricas apresentava apenas 1 ou 2 valores ausentes, enquanto as variáveis categóricas <code>canal</code> e <code>sazonalidade</code> tinham 7 observações faltantes cada.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(dados))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                id        receita_mil     invest_digital invest_tradicional 
                 1                  2                  2                  2 
    num_promotores     taxa_conversao     impressoes_mil                cpc 
                 2                  2                  2                  2 
   num_cliques_mil       duracao_dias              canal       sazonalidade 
                 2                  2                  7                  7 </code></pre>
</div>
</div>
<p>Considerando a importância dessas variáveis para a análise e a quantidade relativamente pequena de dados ausentes, optou-se por remover as observações incompletas. Essa decisão permite manter a integridade e consistência do conjunto de dados, garantindo que o modelo de regressão seja ajustado apenas com informações completas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retirando observações com dados ausentes (NA)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>dados_analise <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(dados)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="estatísticas-descritivas" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="estatísticas-descritivas"><span class="header-section-number">3.2</span> Estatísticas Descritivas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados_analise)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      id             receita_mil    invest_digital invest_tradicional
 Length:200         Min.   : 53.3   Min.   : 2.0   Min.   : 0.00     
 Class :character   1st Qu.:130.4   1st Qu.:17.3   1st Qu.: 5.23     
 Mode  :character   Median :164.4   Median :25.2   Median : 8.34     
                    Mean   :162.6   Mean   :25.3   Mean   : 8.34     
                    3rd Qu.:193.0   3rd Qu.:32.5   3rd Qu.:11.19     
                    Max.   :273.8   Max.   :50.9   Max.   :20.30     
 num_promotores taxa_conversao impressoes_mil        cpc       num_cliques_mil
 Min.   :0.00   Min.   :0.34   Min.   :  49.8   Min.   :1.85   Min.   : 0.5   
 1st Qu.:1.75   1st Qu.:2.03   1st Qu.: 370.8   1st Qu.:2.65   1st Qu.:21.7   
 Median :3.00   Median :2.53   Median : 507.8   Median :2.96   Median :29.2   
 Mean   :2.85   Mean   :2.52   Mean   : 509.6   Mean   :2.98   Mean   :29.8   
 3rd Qu.:4.00   3rd Qu.:3.02   3rd Qu.: 646.6   3rd Qu.:3.29   3rd Qu.:38.9   
 Max.   :7.00   Max.   :4.61   Max.   :1006.9   Max.   :4.37   Max.   :64.3   
  duracao_dias     canal           sazonalidade      
 Min.   : 8.0   Length:200         Length:200        
 1st Qu.:19.0   Class :character   Class :character  
 Median :33.0   Mode  :character   Mode  :character  
 Mean   :33.7                                        
 3rd Qu.:48.0                                        
 Max.   :60.0                                        </code></pre>
</div>
</div>
<p>A análise descritiva das variáveis numéricas permite compreender o comportamento geral dos dados presentes na base analisada.</p>
<p>A variável <code>receita_mil</code> apresentou média próxima de 162 mil unidades monetárias, com valores variando aproximadamente entre 53 e 273. Essa variação indica diferenças significativas no desempenho das campanhas analisadas.</p>
<p>Além da variável resposta, a base contém variáveis relacionadas a investimento em marketing digital e tradicional, métricas de engajamento (cliques e impressões) e características operacionais das campanhas.</p>
</section>
<section id="análise-gráfica" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="análise-gráfica"><span class="header-section-number">3.3</span> Análise Gráfica</h2>
<p>Nesta seção, são apresentados gráficos que permitem visualizar o comportamento das variáveis da base e suas relações com a variável resposta <code>receita_mil</code>. A análise gráfica auxilia na identificação de padrões, tendências, outliers e possíveis relações lineares ou não-lineares, servindo como suporte para a modelagem estatística subsequente.</p>
<section id="histograma" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="histograma"><span class="header-section-number">3.3.1</span> Histograma</h3>
<p>O histograma da variável receita_mil permite observar a distribuição dos valores de receita gerados pelas campanhas. A partir da imagem, podemos notas que a distribuição apresenta formato aproximadamente normal, com a maior concentração de dados entre 100 mil e 200 mil e pico em torno de 170 mil.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">x =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill=</span><span class="st">"steelblue"</span>, <span class="at">color=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribuição da Receita das Campanhas"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Receita (mil)"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequência"</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="boxplot" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="boxplot"><span class="header-section-number">3.3.2</span> Boxplot</h3>
<p>O boxplot da variável receita_mil foi utilizado para identificar possíveis valores extremos (outliers) e analisar a dispersão dos dados em torno da mediana. Esse gráfico permite visualizar a distribuição dos valores de receita e compreender melhor a variabilidade presente no conjunto de dados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">y =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill=</span><span class="st">"orange"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot da variável receita_mil"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Receita (mil)"</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gráficos-de-dispersão" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="gráficos-de-dispersão"><span class="header-section-number">3.3.3</span> Gráficos de Dispersão</h3>
<p>Os gráficos de dispersão entre receita_mil e variáveis como invest_digital e num_cliques_mil permitem avaliar visualmente a possível relação entre a variável resposta e algumas variáveis explicativas. A presença de tendências ascendentes ou descendentes nesses gráficos pode indicar associações lineares entre as variáveis, o que justifica a aplicação de modelos de regressão linear múltipla nas etapas seguintes da análise.</p>
<p>De modo geral, a análise gráfica complementa as estatísticas descritivas, fornecendo uma compreensão mais intuitiva dos dados e auxiliando na identificação de padrões, tendências e possíveis anomalias que podem influenciar os resultados do modelo estatístico.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">x =</span> invest_digital, <span class="at">y =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Receita vs Investimento Digital"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Investimento Digital"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Receita (mil)"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">x =</span> num_cliques_mil, <span class="at">y =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">"lm"</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">color=</span><span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Receita vs Número de Cliques"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Cliques (mil)"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Receita (mil)"</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="análises-bivariadas" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análises Bivariadas</h1>
<section id="variáveis-numéricas" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="variáveis-numéricas"><span class="header-section-number">4.1</span> Variáveis Numéricas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(corrplot)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(corr_matrix, <span class="at">method =</span> <span class="st">"color"</span>, <span class="at">addCoef.col =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Nesta seção são analisadas as relações entre a variável resposta (receita_mil) e as demais variáveis do dataset. O objetivo é identificar possíveis associações entre a receita gerada pelas campanhas e os fatores relacionados ao investimento em marketing e desempenho das campanhas.</p>
<section id="principais-destaques-e-interpretações" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="principais-destaques-e-interpretações"><span class="header-section-number">4.1.1</span> Principais destaques e interpretações</h3>
<ol type="1">
<li><code>receita_mil</code> (variável resposta)</li>
</ol>
<p>Correlação com as demais variáveis:</p>
<ul>
<li><p><code>invest_digital</code> → 0.94 → Correlação muito forte positiva;</p></li>
<li><p><code>impressoes_mil</code> → 0.93 → Correlação muito forte positiva;</p></li>
<li><p><code>num_cliques_mil</code> → 0.90 → Correlação muito forte positiva;</p></li>
<li><p><code>taxa_conversao</code> → 0.13 → Correlação fraca positiva;</p></li>
<li><p><code>invest_tradicional</code> → 0.10 → Correlação fraca positiva;</p></li>
<li><p><code>num_promotores</code> → 0.05 → Correlação muito fraca;</p></li>
<li><p><code>duracao_dias</code> → -0.09 → Correlação fraca negativa;</p></li>
<li><p><code>cpc</code> → -0.53 → Correlação moderada negativa.</p></li>
</ul>
<ol start="2" type="1">
<li>Correlação entre variáveis explicativas</li>
</ol>
<ul>
<li><p><code>invest_digital</code> e <code>impressoes_mil</code> → 0.99 → Correlação extremamente alta;</p></li>
<li><p><code>invest_digital</code> e <code>num_cliques_mil</code> → 0.93 → Correlação muito alta;</p></li>
<li><p><code>impressoes_mil</code> e <code>num_cliques_mil</code> → 0.93 → Correlação muito alta.</p></li>
</ul>
<p>Esses resultados indicam a presença de forte associação entre algumas variáveis explicativas, o que pode caracterizar multicolinearidade. Em especial, as variáveis relacionadas ao desempenho digital das campanhas apresentam correlações muito elevadas entre si, sugerindo que podem carregar informações semelhantes no modelo de regressão. Desse modo, o ideal é escolher entre uma delas.</p>
</section>
</section>
<section id="variáveis-categóricas" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="variáveis-categóricas"><span class="header-section-number">4.2</span> Variáveis Categóricas</h2>
<p>Análise bivariada entre <code>canal</code> e <code>receita_mil</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">x =</span> canal, <span class="at">y =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise bivariada entre a variável categórica <code>canal</code> e a variável numérica <code>receita_mil</code> permite observar diferenças na distribuição da receita entre os diferentes canais de marketing.</p>
<p>Observa-se que campanhas realizadas por meio de <code>Redes Sociais</code> e <code>E-mail</code> apresentam medianas de receita superiores em comparação aos demais canais, sugerindo maior desempenho desses meios na geração de receita. O canal <code>SEO</code> apresenta valores intermediários de receita, enquanto o canal <code>Display</code> apresenta mediana inferior.</p>
<p>Além disso, percebe-se maior variabilidade na receita das campanhas realizadas por <code>E-mail</code> e <code>Redes Sociais</code>, indicando maior dispersão dos resultados obtidos nesses canais.</p>
<p>Análise bivariada entre sazonalidade e receita_mil.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados_analise, <span class="fu">aes</span>(<span class="at">x =</span> sazonalidade, <span class="at">y =</span> receita_mil)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise bivariada entre <code>sazonalidade</code> e <code>receita_mil</code> permite observar diferenças na distribuição da receita das campanhas entre períodos de alta e baixa sazonalidade.</p>
<p>Observa-se que campanhas realizadas em períodos de <code>Alta</code> sazonalidade apresentam mediana de receita superior em comparação aos períodos de <code>Baixa</code> sazonalidade. Além disso, nota-se maior dispersão dos valores de receita nesses períodos, indicando maior variabilidade nos resultados obtidos.</p>
<p>Esses resultados sugerem que fatores sazonais podem influenciar o desempenho das campanhas de marketing, possivelmente devido ao aumento da demanda em determinadas épocas do ano</p>
</section>
</section>
<section id="regressão-linear" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Regressão Linear</h1>
<p>Para explorar o impacto de todas as variáveis sobre a receita (<code>receita_mil</code>), foi ajustado um <strong>modelo de regressão linear múltipla inicial</strong> incluindo todas as variáveis explicativas disponíveis:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(receita_mil <span class="sc">~</span> invest_digital <span class="sc">+</span> cpc <span class="sc">+</span> canal <span class="sc">+</span> sazonalidade <span class="sc">+</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                     num_cliques_mil <span class="sc">+</span> impressoes_mil <span class="sc">+</span> num_promotores <span class="sc">+</span> duracao_dias, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> dados_analise)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ invest_digital + cpc + canal + sazonalidade + 
    num_cliques_mil + impressoes_mil + num_promotores + duracao_dias, 
    data = dados_analise)

Residuals:
    Min      1Q  Median      3Q     Max 
-28.290  -7.534  -0.063   6.801  30.272 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         6.15e+01   8.18e+00    7.51  2.2e-12 ***
invest_digital      4.32e+00   4.89e-01    8.82  7.6e-16 ***
cpc                 9.47e-01   2.16e+00    0.44     0.66    
canalE-mail         5.95e-01   2.65e+00    0.22     0.82    
canalRedes Sociais  1.08e+01   2.49e+00    4.33  2.4e-05 ***
canalSEO           -1.59e+00   2.78e+00   -0.57     0.57    
sazonalidadeBaixa  -1.63e+01   1.60e+00  -10.20  &lt; 2e-16 ***
num_cliques_mil     1.92e-01   1.66e-01    1.16     0.25    
impressoes_mil     -3.31e-02   2.56e-02   -1.29     0.20    
num_promotores      1.74e+00   4.20e-01    4.15  5.1e-05 ***
duracao_dias       -6.86e-04   5.03e-02   -0.01     0.99    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11 on 189 degrees of freedom
Multiple R-squared:  0.948, Adjusted R-squared:  0.945 
F-statistic:  341 on 10 and 189 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
<p>O modelo inicial revelou que as variáveis <code>invest_digital</code> e <code>num_promotores</code> apresentaram efeitos positivos e estatisticamente significativos sobre a receita_mil, indicando que aumentos nessas variáveis estão associados a incrementos na receita das campanhas.</p>
<p>As variáveis <code>cpc</code>, <code>num_cliques_mil</code>, <code>impressoes_mil</code> e <code>duracao_dias</code>, embora incluídas no modelo, não apresentaram efeito estatisticamente significativo, sugerindo sobreposição ou redundância de informação com outras variáveis do modelo.</p>
<p>Entre as variáveis categóricas, o canal de marketing mostrou que campanhas realizadas via Redes Sociais geraram aumento significativo na receita em comparação ao canal de referência (Display), enquanto E-mail e SEO não apresentaram efeito significativo.</p>
<blockquote class="blockquote">
<p>O modelo final apresentou um R² ajustado de 0.945, indicando que aproximadamente 94,5% da variação na receita das campanhas é explicada pelas variáveis incluídas no modelo.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="sc">%&gt;%</span> <span class="fu">tbl_regression</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="sxairhkajr" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#sxairhkajr table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#sxairhkajr thead, #sxairhkajr tbody, #sxairhkajr tfoot, #sxairhkajr tr, #sxairhkajr td, #sxairhkajr th {
  border-style: none;
}

#sxairhkajr p {
  margin: 0;
  padding: 0;
}

#sxairhkajr .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#sxairhkajr .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#sxairhkajr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#sxairhkajr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#sxairhkajr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sxairhkajr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sxairhkajr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#sxairhkajr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#sxairhkajr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#sxairhkajr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#sxairhkajr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#sxairhkajr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#sxairhkajr .gt_spanner_row {
  border-bottom-style: hidden;
}

#sxairhkajr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#sxairhkajr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#sxairhkajr .gt_from_md > :first-child {
  margin-top: 0;
}

#sxairhkajr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#sxairhkajr .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#sxairhkajr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#sxairhkajr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#sxairhkajr .gt_row_group_first td {
  border-top-width: 2px;
}

#sxairhkajr .gt_row_group_first th {
  border-top-width: 2px;
}

#sxairhkajr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sxairhkajr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#sxairhkajr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#sxairhkajr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sxairhkajr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#sxairhkajr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#sxairhkajr .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#sxairhkajr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#sxairhkajr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#sxairhkajr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sxairhkajr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sxairhkajr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#sxairhkajr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#sxairhkajr .gt_left {
  text-align: left;
}

#sxairhkajr .gt_center {
  text-align: center;
}

#sxairhkajr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#sxairhkajr .gt_font_normal {
  font-weight: normal;
}

#sxairhkajr .gt_font_bold {
  font-weight: bold;
}

#sxairhkajr .gt_font_italic {
  font-style: italic;
}

#sxairhkajr .gt_super {
  font-size: 65%;
}

#sxairhkajr .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#sxairhkajr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#sxairhkajr .gt_indent_1 {
  text-indent: 5px;
}

#sxairhkajr .gt_indent_2 {
  text-indent: 10px;
}

#sxairhkajr .gt_indent_3 {
  text-indent: 15px;
}

#sxairhkajr .gt_indent_4 {
  text-indent: 20px;
}

#sxairhkajr .gt_indent_5 {
  text-indent: 25px;
}

#sxairhkajr .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#sxairhkajr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Beta</strong></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">invest_digital</td>
<td class="gt_row gt_center" headers="estimate">4.3</td>
<td class="gt_row gt_center" headers="conf.low">3.4, 5.3</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">cpc</td>
<td class="gt_row gt_center" headers="estimate">0.95</td>
<td class="gt_row gt_center" headers="conf.low">-3.3, 5.2</td>
<td class="gt_row gt_center" headers="p.value">0.7</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">canal</td>
<td class="gt_row gt_center" headers="estimate"><br>
</td>
<td class="gt_row gt_center" headers="conf.low"><br>
</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Display</td>
<td class="gt_row gt_center" headers="estimate">—</td>
<td class="gt_row gt_center" headers="conf.low">—</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;E-mail</td>
<td class="gt_row gt_center" headers="estimate">0.60</td>
<td class="gt_row gt_center" headers="conf.low">-4.6, 5.8</td>
<td class="gt_row gt_center" headers="p.value">0.8</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Redes Sociais</td>
<td class="gt_row gt_center" headers="estimate">11</td>
<td class="gt_row gt_center" headers="conf.low">5.9, 16</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;SEO</td>
<td class="gt_row gt_center" headers="estimate">-1.6</td>
<td class="gt_row gt_center" headers="conf.low">-7.1, 3.9</td>
<td class="gt_row gt_center" headers="p.value">0.6</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">sazonalidade</td>
<td class="gt_row gt_center" headers="estimate"><br>
</td>
<td class="gt_row gt_center" headers="conf.low"><br>
</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Alta</td>
<td class="gt_row gt_center" headers="estimate">—</td>
<td class="gt_row gt_center" headers="conf.low">—</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;Baixa</td>
<td class="gt_row gt_center" headers="estimate">-16</td>
<td class="gt_row gt_center" headers="conf.low">-19, -13</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">num_cliques_mil</td>
<td class="gt_row gt_center" headers="estimate">0.19</td>
<td class="gt_row gt_center" headers="conf.low">-0.14, 0.52</td>
<td class="gt_row gt_center" headers="p.value">0.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">impressoes_mil</td>
<td class="gt_row gt_center" headers="estimate">-0.03</td>
<td class="gt_row gt_center" headers="conf.low">-0.08, 0.02</td>
<td class="gt_row gt_center" headers="p.value">0.2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">num_promotores</td>
<td class="gt_row gt_center" headers="estimate">1.7</td>
<td class="gt_row gt_center" headers="conf.low">0.91, 2.6</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">duracao_dias</td>
<td class="gt_row gt_center" headers="estimate">0.00</td>
<td class="gt_row gt_center" headers="conf.low">-0.10, 0.10</td>
<td class="gt_row gt_center" headers="p.value">&gt;0.9</td>
</tr>
</tbody><tfoot>
<tr class="gt_sourcenotes odd">
<td colspan="4" class="gt_sourcenote">Abbreviation: CI = Confidence Interval</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
<section id="multicolinearidade" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="multicolinearidade"><span class="header-section-number">5.1</span> Multicolinearidade</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 GVIF Df GVIF^(1/(2*Df))
invest_digital  50.76  1            7.12
cpc              1.60  1            1.26
canal            1.09  3            1.02
sazonalidade     1.04  1            1.02
num_cliques_mil  8.39  1            2.90
impressoes_mil  45.75  1            6.76
num_promotores   1.04  1            1.02
duracao_dias     1.05  1            1.02</code></pre>
</div>
</div>
<p><code>cpc</code>, <code>canal</code>, <code>sazonalidade</code>, <code>num_promotores</code> e <code>duracao_dias</code> apresentam VIFs próximos de 1, indicando ausência de multicolinearidade. Já <code>invest_digital</code>, <code>impressoes_mil</code> e <code>num_cliques_mil</code> apresentam VIFs elevados (7,12; 6,76 e 2,90, respectivamente), evidenciando forte correlação entre essas variáveis.</p>
<p>Para evitar redundância e instabilidade nos coeficientes da regressão, iremos avaliar quais dessas variáveis podem ser removidas, mantendo apenas aquelas que contribuem de forma relevante e estável para o modelo.</p>
<section id="modelo-a-sem-num_cliques_mil" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="modelo-a-sem-num_cliques_mil"><span class="header-section-number">5.1.1</span> Modelo A: Sem <code>num_cliques_mil</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>modelo_A <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo, <span class="sc">~</span> . <span class="sc">-</span>num_cliques_mil)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_A)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ invest_digital + cpc + canal + sazonalidade + 
    impressoes_mil + num_promotores + duracao_dias, data = dados_analise)

Residuals:
    Min      1Q  Median      3Q     Max 
-25.352  -7.632   0.062   6.700  31.603 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         59.71028    8.04410    7.42  3.7e-12 ***
invest_digital       4.47148    0.47092    9.50  &lt; 2e-16 ***
cpc                  1.41375    2.11894    0.67     0.51    
canalE-mail          0.43467    2.65142    0.16     0.87    
canalRedes Sociais  10.80091    2.49447    4.33  2.4e-05 ***
canalSEO            -1.61409    2.77762   -0.58     0.56    
sazonalidadeBaixa  -16.47522    1.59241  -10.35  &lt; 2e-16 ***
impressoes_mil      -0.02912    0.02538   -1.15     0.25    
num_promotores       1.78628    0.41875    4.27  3.1e-05 ***
duracao_dias         0.00377    0.05025    0.08     0.94    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11 on 190 degrees of freedom
Multiple R-squared:  0.947, Adjusted R-squared:  0.945 
F-statistic:  379 on 9 and 190 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="modelo-b-sem-impressoes_mil" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="modelo-b-sem-impressoes_mil"><span class="header-section-number">5.1.2</span> Modelo B: Sem <code>impressoes_mil</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>modelo_B <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo, <span class="sc">~</span> . <span class="sc">-</span>impressoes_mil)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_B)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ invest_digital + cpc + canal + sazonalidade + 
    num_cliques_mil + num_promotores + duracao_dias, data = dados_analise)

Residuals:
   Min     1Q Median     3Q    Max 
-27.98  -7.48  -0.39   6.98  30.52 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         60.43917    8.15530    7.41  4.0e-12 ***
invest_digital       3.74601    0.21312   17.58  &lt; 2e-16 ***
cpc                  0.57753    2.13977    0.27     0.79    
canalE-mail          0.87841    2.64831    0.33     0.74    
canalRedes Sociais  11.04191    2.48872    4.44  1.5e-05 ***
canalSEO            -1.25915    2.76837   -0.45     0.65    
sazonalidadeBaixa  -16.14851    1.59654  -10.11  &lt; 2e-16 ***
num_cliques_mil      0.16352    0.16498    0.99     0.32    
num_promotores       1.74893    0.42079    4.16  4.9e-05 ***
duracao_dias         0.00526    0.05023    0.10     0.92    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11 on 190 degrees of freedom
Multiple R-squared:  0.947, Adjusted R-squared:  0.945 
F-statistic:  378 on 9 and 190 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="modelo-c-sem-invest_digital" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="modelo-c-sem-invest_digital"><span class="header-section-number">5.1.3</span> Modelo C: Sem <code>invest_digital</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>modelo_C <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo, <span class="sc">~</span> . <span class="sc">-</span>invest_digital)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_C)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ cpc + canal + sazonalidade + num_cliques_mil + 
    impressoes_mil + num_promotores + duracao_dias, data = dados_analise)

Residuals:
   Min     1Q Median     3Q    Max 
-34.56  -7.83  -1.18   7.82  36.21 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         68.6658     9.6448    7.12  2.2e-11 ***
cpc                 -4.7008     2.4383   -1.93   0.0554 .  
canalE-mail          3.3140     3.1220    1.06   0.2898    
canalRedes Sociais  12.6509     2.9426    4.30  2.7e-05 ***
canalSEO             0.9851     3.2703    0.30   0.7636    
sazonalidadeBaixa  -14.7605     1.8823   -7.84  3.1e-13 ***
num_cliques_mil      0.5952     0.1893    3.14   0.0019 ** 
impressoes_mil       0.1701     0.0132   12.91  &lt; 2e-16 ***
num_promotores       1.6450     0.4976    3.31   0.0011 ** 
duracao_dias         0.0201     0.0596    0.34   0.7365    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13.1 on 190 degrees of freedom
Multiple R-squared:  0.926, Adjusted R-squared:  0.922 
F-statistic:  264 on 9 and 190 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="modelo-d-sem-num_cliques_mil-e-impressoes_mil" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="modelo-d-sem-num_cliques_mil-e-impressoes_mil"><span class="header-section-number">5.1.4</span> Modelo D: Sem <code>num_cliques_mil</code> e <code>impressoes_mil</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>modelo_D <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo, <span class="sc">~</span> . <span class="sc">-</span>num_cliques_mil <span class="sc">-</span> impressoes_mil)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_D)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ invest_digital + cpc + canal + sazonalidade + 
    num_promotores + duracao_dias, data = dados_analise)

Residuals:
   Min     1Q Median     3Q    Max 
-25.47  -7.38  -0.32   6.78  31.65 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         59.0196     8.0282    7.35  5.6e-12 ***
invest_digital       3.9399     0.0845   46.60  &lt; 2e-16 ***
cpc                  1.0197     2.0927    0.49     0.63    
canalE-mail          0.7099     2.6427    0.27     0.79    
canalRedes Sociais  11.0293     2.4886    4.43  1.6e-05 ***
canalSEO            -1.3151     2.7677   -0.48     0.64    
sazonalidadeBaixa  -16.3151     1.5876  -10.28  &lt; 2e-16 ***
num_promotores       1.7861     0.4191    4.26  3.2e-05 ***
duracao_dias         0.0085     0.0501    0.17     0.87    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11 on 191 degrees of freedom
Multiple R-squared:  0.947, Adjusted R-squared:  0.945 
F-statistic:  425 on 8 and 191 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
<section id="modelo-e-sem-invest_digital-e-impressoes_mil" class="level3" data-number="5.1.5">
<h3 data-number="5.1.5" class="anchored" data-anchor-id="modelo-e-sem-invest_digital-e-impressoes_mil"><span class="header-section-number">5.1.5</span> Modelo E: Sem <code>invest_digital</code> e <code>impressoes_mil</code></h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>modelo_E <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo, <span class="sc">~</span> . <span class="sc">-</span>invest_digital <span class="sc">-</span> impressoes_mil)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_E)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ cpc + canal + sazonalidade + num_cliques_mil + 
    num_promotores + duracao_dias, data = dados_analise)

Residuals:
   Min     1Q Median     3Q    Max 
 -65.5  -10.7   -1.1   11.6   41.8 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        122.6501    11.8752   10.33  &lt; 2e-16 ***
cpc                -14.9271     3.1509   -4.74  4.2e-06 ***
canalE-mail          5.3778     4.2604    1.26   0.2084    
canalRedes Sociais  12.3548     4.0207    3.07   0.0024 ** 
canalSEO             1.2584     4.4685    0.28   0.7785    
sazonalidadeBaixa  -13.3793     2.5679   -5.21  4.9e-07 ***
num_cliques_mil      2.8255     0.1058   26.71  &lt; 2e-16 ***
num_promotores       1.1220     0.6777    1.66   0.0994 .  
duracao_dias        -0.0670     0.0809   -0.83   0.4087    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 17.8 on 191 degrees of freedom
Multiple R-squared:  0.861, Adjusted R-squared:  0.855 
F-statistic:  148 on 8 and 191 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="seleção-do-modelo" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="seleção-do-modelo"><span class="header-section-number">5.2</span> Seleção do Modelo</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparando todos os modelos</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_A, modelo_B, modelo_C, modelo_D, modelo_E)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         df  AIC
modelo_A 11 1539
modelo_B 11 1540
modelo_C 11 1607
modelo_D 10 1539
modelo_E 10 1731</code></pre>
</div>
</div>
<p>Diante dessa análise, optou-se pelo modelo D, que apresentou o menor valor de AIC entre os modelos mais bem ajustados e menor número de parâmetros, sendo mais parcimonioso. Além disso, o modelo atende aos pressupostos do modelo linear múltiplo, sendo considerado o mais apropriado para explicar os dados.</p>
<p>Para simplificar ainda mais o modelo e facilitar a interpretação dos coeficientes, optou-se por remover as variáveis com baixa significância estatística, que não contribuem de forma relevante para a explicação de <code>receita_mil</code>, vistando melhorar a interpretabilidade.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(receita_mil <span class="sc">~</span> invest_digital <span class="sc">+</span> cpc <span class="sc">+</span> canal <span class="sc">+</span> sazonalidade, <span class="at">data =</span> dados_analise)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = receita_mil ~ invest_digital + cpc + canal + sazonalidade, 
    data = dados_analise)

Residuals:
   Min     1Q Median     3Q    Max 
-25.71  -8.12  -0.69   7.12  33.55 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         62.9987     8.2024    7.68  7.8e-13 ***
invest_digital       3.9374     0.0879   44.81  &lt; 2e-16 ***
cpc                  1.3293     2.1741    0.61     0.54    
canalE-mail          1.0167     2.7392    0.37     0.71    
canalRedes Sociais  11.7972     2.5641    4.60  7.6e-06 ***
canalSEO            -1.9934     2.8734   -0.69     0.49    
sazonalidadeBaixa  -15.8000     1.6454   -9.60  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 11.5 on 193 degrees of freedom
Multiple R-squared:  0.942, Adjusted R-squared:  0.94 
F-statistic:  520 on 6 and 193 DF,  p-value: &lt;2e-16</code></pre>
</div>
</div>
<p>A remoção das variáveis com baixa significância estatística resultou em uma pequena redução no R², de 0,945 para 0,94. Essa diferença é mínima, indicando que as variáveis removidas contribuíam pouco para a explicação da variável resposta.</p>
</section>
</section>
<section id="análise-dos-pressupostos" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Análise dos pressupostos</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Relatorio_marketing_files/figure-html/check_model_plot-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Posterior Predictive Check:</strong> A linha da densidade dos dados preditos (verde) acompanha bem a dos dados observados (azul). O modelo apresenta boa capacidade preditiva.</li>
<li><strong>Linearity:</strong> Os resíduos estão dispersos aleatoriamente ao redor da linha horizontal, atendendo ao pressuposto da linearidade.</li>
<li><strong>Homogeneity of Variance</strong>: A linha de referência é plana e a dispersão vertical dos resíduos se mantém constante. O pressuposto de homocedasticidade foi atendido.</li>
<li><strong>Normality of Residuals</strong>: Os pontos seguem aproximadamente a linha de referência, com pequenas divergências nas extremidades. Há leve violação da normalidade dos resíduos.</li>
<li><strong>Influential Observations</strong>: Nenhum ponto ultrapassa o limite das linhas</li>
<li><strong>Colinearity</strong>: Todos os valores de VIF estão abaixo do limite crítico de 5. Não há evidência de multicolinearidade entre os preditores.</li>
</ul>
<p>Desse modo, os pressupostos foram considerados atendidos. Adicionalmente, foi calculado o Fator de Inflação de Variância para verificar a multicolinearidade entre os preditores.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               GVIF Df GVIF^(1/(2*Df))
invest_digital 1.51  1            1.23
cpc            1.50  1            1.22
canal          1.03  3            1.00
sazonalidade   1.02  1            1.01</code></pre>
</div>
</div>
<p>Todos os valores de VIF estão próximos de 1, sendo assim, não há evicência de multicolinearidade.</p>
</section>
<section id="estimativas" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Estimativas</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>estimativa <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">invest_digital =</span> <span class="dv">10</span>,       </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cpc =</span> <span class="dv">2</span>,                   </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">canal =</span> <span class="st">"Redes Sociais"</span>,   </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sazonalidade =</span> <span class="st">"Alta"</span>      </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> estimativa, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fit lwr upr
1 117 110 124</code></pre>
</div>
</div>
<p>Considerando uma campanha com investimento digital de 10 mil, CPC de 2, canal “Redes Sociais” e período de alta sazonalidade, estima-se que a receita média seja de aproximadamente 117 mil. Com 95% de confiança, espera-se que o valor médio real da receita esteja entre 110 e 124 mil.</p>
</section>
<section id="previsões" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Previsões</h1>
<p>Utilizaremos o modelo para realizar a predição em dois cenários hipotéticos</p>
<p><strong>Cenário 1</strong>: Investimento digital de 10 mil, CPC 2, canal “Redes Sociais” e sazonalidade alta</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>cenario1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">invest_digital =</span> <span class="dv">10</span>,            </span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cpc =</span> <span class="dv">2</span>,                        </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">canal =</span> <span class="st">"Redes Sociais"</span>,        </span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sazonalidade =</span> <span class="st">"Alta"</span>          </span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> cenario1, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fit lwr upr
1 117 110 124</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> cenario1, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  fit  lwr upr
1 117 93.2 140</code></pre>
</div>
</div>
<ul>
<li><p>Previsão de Receita: R$ 117 mil</p></li>
<li><p>Intervalo de Confiança (95%): A média de receita para campanhas com este perfil está entre R$ 110 mil e R$ 124 mil</p></li>
<li><p>Intervalo de Predição (95%): A receita de uma nova campanha com este perfil estará entre R$ 93,2 mil e R$ 140 mil</p></li>
</ul>
<p><strong>Cenário 2</strong>: Investimento digital de 5 mil, CPC 3, canal “E-mail” e sazonalidade baixa</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>cenario2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">invest_digital =</span> <span class="dv">5</span>,             </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cpc =</span> <span class="dv">3</span>,                        </span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">canal =</span> <span class="st">"E-mail"</span>,               </span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">sazonalidade =</span> <span class="st">"Baixa"</span>          </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> cenario2, <span class="at">interval =</span> <span class="st">"confidence"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 71.9 66.9 76.9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(modelo, <span class="at">newdata =</span> cenario2, <span class="at">interval =</span> <span class="st">"prediction"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   fit  lwr  upr
1 71.9 48.7 95.1</code></pre>
</div>
</div>
<ul>
<li><p>Previsão de Receita: R$ 71 mil</p></li>
<li><p>Intervalo de Confiança (95%): A média de receita para campanhas com este perfil está entre R$ 66.9 mil e R$ 76.9 mil</p></li>
<li><p>Intervalo de Predição (95%): A receita de uma nova campanha com este perfil estará entre R$ 48,7 mil e R$ 95,1 mil</p></li>
</ul>
</section>
<section id="conclusão" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Conclusão</h1>
<p>Este relatório apresenta uma análise dos principais fatores que influenciam a receita gerada por campanhas de marketing, utilizando técnicas de exploração de dados e modelagem estatística. Após o tratamento e a limpeza dos dados, foram selecionadas variáveis explicativas com base em critérios estatísticos e conceituais, priorizando aquelas com maior capacidade de explicar a variação na receita.</p>
<p>O modelo de regressão linear múltipla ajustado apresentou excelente ajuste (R² ajustado = 0,94), ausência de multicolinearidade e atendimento satisfatório aos principais pressupostos do modelo, com pequenas violações que não comprometem sua validade. As variáveis investimento digital, canal de marketing e sazonalidade mostraram influência significativa sobre a receita, enquanto o CPC não apresentou efeito estatisticamente relevante.</p>
<p>Foram realizadas estimativas e predições em cenários hipotéticos, permitindo interpretar o impacto prático de diferentes estratégias de investimento, canais e períodos de campanha. Os resultados evidenciam que campanhas com investimentos mais elevados em canais digitais, especialmente Redes Sociais, e em períodos de alta sazonalidade tendem a gerar maiores receitas, enquanto campanhas em canais com menor desempenho ou em baixa sazonalidade apresentam resultados inferiores.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>